apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres-cluster
spec:
  postgresVersion: 16
  users:
    - name: postgres
    - name: keycloak-admin
      databases:  
        - keycloak
      options: 'OWNER'
    - name: dicom-admin
      databases:
        - dicom-store
      options: 'OWNER'
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
        schedules:
          full: "0 2 * * *"
